spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.10.10:35432/supervisor
    username: supervisor
    password: supervisor

  data:
    redis:
      host: 192.168.10.10
      port: 36379
      password: redis

logging:
  level:
    root: info
    com.unknown.supervisor: debug

knife4j:
  enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# JWT配置
app:
  jwt:
    secret: supervisor-jwt-secret-key-for-authentication-and-authorization
    token-prefix: "Bearer "
    header-name: "Authorization"
    token-param: "token"